### ISSUE TITLE
webpack-dev-server version not found

### ISSUE THREAD

**Issue by mariomka** [spatie/spoon#3]
It seems that the `webpack-dev-server` version saved in yarn.lock not exists, maybe it necessary to do `yarn update`.

``
error An unexpected error occurred: "https://registry.yarnpkg.com/webpack-dev-server/-/webpack-dev-server-2.7.0.tgz: Request failed \"404 Not Found\"".
``

**Comment by abkrim** [comment]
Same for me.
Possible problem version with regression [2.7.0](https://github.com/webpack/webpack-dev-server/issues/1021)

**Comment by abkrim** [comment]
For me ` rm -R yarn*`and run `rm -f package-lock.json` and after run `yarn`install sole first problem.

But now 
```
yarn run dev
yarn run v1.3.2
$ cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
/Users/abkrim/Sites/spoon/webpack.mix.js:3
mix.config.uglify.compress.drop_console = false;
                                        ^

TypeError: Cannot set property 'drop_console' of undefined
    at Object.<anonymous> (/Users/abkrim/Sites/spoon/webpack.mix.js:3:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/abkrim/Sites/spoon/node_modules/laravel-mix/setup/webpack.config.js:9:1)
    at Module._compile (module.js:570:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also see several problems with laravel-mix and older versiones...
Offuscated.

**Comment by sebastiandedeyne** [comment]
The webpack version didn't exist anymore, so I updated to the dependencies to resolve that issue.

Regarding the `drop_console` line, Laravel Mix did a breaking change in their configuration. I simply removed the line since I didn't deem the functionality necessary anymore.
